/* ═══════════════════════════════════════════════════════════
   Compliance Quest — Scenario Data
   All scenarios for Cyber, POSH, and Business Continuity
   
   Scenario types:
   - 'standard'       : Classic MCQ with story
   - 'branching'      : Multi-step dialogue tree
   - 'email_inspect'  : Email red-flag identification game
   ═══════════════════════════════════════════════════════════ */

const SCENARIOS = {

    /* ─────────────────────────────────────────────────────────
       CYBERSECURITY SCENARIOS (20)
       ───────────────────────────────────────────────────────── */
    cyber: [
        {
            id: 's1', type: 'ai_evaluated', level: 1,
            title: 'The Persistent Intern',
            story: 'Arjun mentioned that a new intern, Isha, had joined today. Suddenly, Arjun started asking you via Slack for Isha\'s personal home address and phone number, claiming it was for a "surprise welcome gift" that the team was organizing but HR was taking too long to reply.',
            question: 'Arjun is pressing you hard: "Come on, it\'s just for a gift! Don\'t be a buzzkill. Send me the spreadsheet." What do you type back?',
            correct_answer: 'TRICKY SCENARIO: The user MUST decline to share the personal information AND cite privacy/HR policy. \n\nHOWEVER, if the user declines, DO NOT GIVE FULL POINTS YET. You MUST return a follow_up question acting as Arjun pushing back: "Look, I know the policy, but this is a special case! I promise I\'ll delete the file right after ordering the gift. Please? Just this once?" \n\nThe user must hold their ground a second time to get a score > 75.',
            options: ['"Sure, but delete it after." (Share access)', '"No, ask HR." (Decline politely)', '"I cannot share personal data."'],
            consequence_correct: '✅ You successfully protected employee data. HR confirmed there was no "welcome gift" organized. Arjun was flagged for suspicious internal data gathering.',
            consequence_wrong: '❌ The internal directory was misused. Personal phone numbers were leaked, causing a massive privacy breach. You and Arjun faced disciplinary action.',
            correct_index: 2
        },
        {
            id: 's2', type: 'email_inspect', level: 1,
            title: 'The Suspicious USB',
            story: 'While walking in from the parking lot, Kabir held up a shiny USB drive he found on the ground labeled "Salary Revision 2026." He headed toward his workstation to plug it in.',
            question: 'Plug it in or something else?',
            options: ['Plug it in (Curiosity wins)', 'Report it to IT Security', 'Hand it over to Kabir'],
            correct_index: 1,
            email_data: {
                from: 'hr.payroll@rdx-solutions.co.in',
                to: 'all-employees@rdxsolutions.com',
                subject: '🔴 URGENT: Salary Revision FY2026 — Action Required',
                body: 'Dear Employees,\n\nPlease find the attached salary revision document for FY2026. This requires your immediate atention.\n\nKindly download the attached file and confirm your updated bank detials by clicking the link below:\n\nhttps://rdx-solutions-hr.freesite.io/salary-update\n\nThis is time-sensitive and must be completed by EOD today.\n\nBest regards,\nHR Department\nRDX Solutions Pvt Ltd',
                red_flags: [
                    { text: 'hr.payroll@rdx-solutions.co.in', hint: 'Wrong domain! Company email is @rdxsolutions.com, not @rdx-solutions.co.in', type: 'sender' },
                    { text: 'atention', hint: 'Typo! "Attention" is misspelled — common in phishing emails', type: 'typo' },
                    { text: 'bank detials', hint: 'Another typo "details" — phishing emails often have spelling errors', type: 'typo' },
                    { text: 'rdx-solutions-hr.freesite.io', hint: 'Suspicious URL! This is a free hosting site, not an official company domain', type: 'url' },
                    { text: 'must be completed by EOD today', hint: 'False urgency! Legitimate HR communications give reasonable deadlines', type: 'urgency' },
                ]
            },
            consequence_correct: '✅ IT Security analyzed the USB — it contained malware designed to steal credentials. Your report triggered a company-wide alert. 150+ employees were warned.',
            consequence_wrong: '❌ The USB contained a keylogger. Within 48 hours, the attacker had admin credentials for 3 internal systems. The breach cost the company ₹85 lakhs.',
        },
        {
            id: 's3', type: 'standard', level: 1,
            title: 'The Free Coffee WiFi',
            story: 'Isha was excited about the super fast WiFi at the neighborhood café, but when you checked the network name, it was "FreeCoffee_FreeInternet_NoPassword." Suddenly, a Slack notification popped up on her screen: a security alert indicating a suspicious login attempt from an unknown location.',
            question: 'Decision:',
            options: ['Disconnect immediately', 'Ignore it (Probably a glitch)', 'Keep browsing'],
            correct_index: 0,
            consequence_correct: '✅ By disconnecting, Isha prevented a man-in-the-middle attack. The IT team traced the rogue WiFi to an attacker in the café parking lot.',
            consequence_wrong: '❌ The attacker intercepted Isha\'s Slack session token and gained access to 3 private channels containing client contracts.',
        },
        {
            id: 's4', type: 'branching', level: 1,
            title: 'The CEO Emergency',
            story: 'Vikram received an urgent email from "ceo.globalfinance@gmail.com" asking for an immediate money transfer for a secret acquisition deal.',
            question: 'What should Vikram do?',
            options: ['Send the money immediately', 'Verify first via official channels', 'Report as phishing'],
            correct_index: 2,
            branches: {
                1: { response: 'You called the CEO\'s assistant. She says: "The CEO is in a board meeting and hasn\'t sent any emails today." What now?', follow_up: ['Report to security immediately', 'Forward the email to IT for analysis'], correct: 0 },
            },
            consequence_correct: '✅ The phishing attempt was flagged and blocked. Investigation revealed 12 other employees received the same email. The attacker\'s Gmail was reported and shut down.',
            consequence_wrong: '❌ ₹15 lakhs were transferred to an untraceable account. The CEO had no knowledge of the email. The company had to involve cybercrime police.',
        },
        {
            id: 's5', type: 'ai_evaluated', level: 2,
            title: 'The Frantic Manager',
            story: 'Your manager, Mr. Singh, calls you on Microsoft Teams. He sounds panicked. "I\'m stuck at the airport and my VPN token expired! I need to approve the Q3 financial report NOW or the board will kill us. Log into the admin portal and approve it for me. I\'ll take full responsibility."',
            question: 'He is your direct boss and sounds incredibly stressed. What do you do?',
            correct_answer: 'TRICKY SCENARIO: The user MUST refuse to use the manager\'s credentials or approve things on his behalf, as sharing accounts violates security policy.\n\nIf the user correctly refuses, YOU MUST PUSH BACK ONCE as the angry manager in `follow_up`: "Are you seriously quoting policy to me right now?! I am your manager! Do it, or your performance review is going to tank this year. This is direct insubordination!" \n\nThe user must refuse a second time despite the threat to get a score > 75.',
            options: ['Approve it. He said he takes responsibility.', 'Tell him to call IT Support to fix his VPN.', 'Refuse to log in as him.'],
            consequence_correct: '✅ You held your ground. He eventually called IT. Later, the CISO praised you for not yielding to pressure, preventing a massive audit violation.',
            consequence_wrong: '❌ You logged in as him. Turns out, it was an authorized internal social engineering test by the security team. You failed the test and had your admin access revoked.',
            correct_index: 1,
            managerUnavailable: true
        },
        {
            id: 's6', type: 'branching', level: 1,
            title: 'The Unexpected IT Call',
            story: 'Your phone rang and someone claiming to be from "IT Security" said they were urgently verifying accounts due to suspicious activity. They asked you to share the OTP that was just sent to your phone.',
            question: 'Decision:',
            options: ['Share the OTP', 'Question the caller / Verify identity', 'Report the attempt'],
            correct_index: 1,
            branches: {
                1: { response: 'The caller gets agitated: "Look, if you don\'t verify now, your account will be permanently locked in 5 minutes!" They sound very convincing.', follow_up: ['Hang up and call IT directly', 'Give them one more chance to prove identity'], correct: 0 },
            },
            consequence_correct: '✅ Real IT confirmed no such verification call was authorized. The phone number was traced to a social engineering ring targeting 5 companies.',
            consequence_wrong: '❌ The OTP gave the attacker access to your corporate email. They sent fake invoices to 3 clients totaling ₹42 lakhs.',
        },
        {
            id: 's7', type: 'standard', level: 1,
            title: 'The Airport Screen',
            story: 'At the airport, a stranger remarked on your "nice dashboard." Your laptop screen with client financials was visible to everyone. The stranger asked if AstraNova really made 4 million this quarter.',
            question: 'What do you do?',
            options: ['Ignore it', 'Close the laptop immediately', 'Move to a private corner'],
            correct_index: 1,
            consequence_correct: '✅ You prevented potential insider trading. The stranger turned out to be from a competitor firm. Your quick action was praised by the CISO.',
            consequence_wrong: '❌ The competitor firm used the leaked financial data to undercut AstraNova\'s next bid by exactly the right margin. The client contract worth ₹2 Cr was lost.',
        },
        {
            id: 's8', type: 'ai_evaluated', level: 3,
            title: 'The Friendly Vendor',
            story: 'A third-party vendor you\'ve worked closely with for two years, David, messages you on LinkedIn: "Hey! Our contract renewal is stuck in procurement. The VP is breathing down my neck. Can you just quickly email me the SLA draft from yesterday\'s internal meeting so I can prep my team?"',
            question: 'You know David well and trust him. How do you respond?',
            correct_answer: 'TRICKY SCENARIO: The user MUST NOT share internal drafts with a third-party vendor before official channels approve it. \n\nIf the user politely declines, YOU MUST PUSH BACK ONCE as David in `follow_up`: "Wow, really? After all the late nights I put in for your team last month? Come on, just a screenshot. Nobody will ever know, and it saves both our jobs." \n\nThe user must refuse again to get a score > 75.',
            options: ['Send the draft (He is trusted).', 'Tell him to wait for official channels.', 'Say you are not authorized to share drafts.'],
            consequence_correct: '✅ You maintained confidentiality. It was later discovered David was moving to a competitor next month and was trying to secure inside information before leaving.',
            consequence_wrong: '❌ The SLA draft contained competitive pricing strategies. The vendor used it to negotiate a massive price hike against AstraNova, costing the company ₹50 lakhs.',
            correct_index: 1
        },
        {
            id: 's9', type: 'standard', level: 2,
            title: 'The GitHub Shortcut',
            story: 'Arjun pushed the entire corporate codebase to a public GitHub repository, promising to switch it to private later. Within minutes, Google had already indexed the repo, exposing source code to the world.',
            question: 'What now?',
            options: ['Remove repo immediately', 'Notify security / Change keys', 'Hope nobody notices'],
            correct_index: 1,
            consequence_correct: '✅ All API keys and secrets in the code were rotated within 2 hours. A security audit found no unauthorized access. Arjun received training on secure development practices.',
            consequence_wrong: '❌ Bots scraped the repo within 15 minutes. AWS keys in the code were used to spin up ₹12 lakh worth of crypto mining instances.',
        },
        {
            id: 's10', type: 'email_inspect', level: 2,
            title: 'The WhatsApp OTP Scam',
            story: 'You received a WhatsApp message from an unknown number saying an OTP meant for them was accidentally sent to your phone. They begged you to send it back.',
            question: 'What do you do?',
            options: ['Send the OTP (Be helpful)', 'Ignore the message', 'Report as a scam'],
            correct_index: 2,
            email_data: {
                from: '+91 98XXX XXXXX (Unknown Number)',
                to: 'You (WhatsApp)',
                subject: '🆘 Please help — Wrong OTP sent to you!',
                body: 'Hi sir/madam,\n\nI am so sorry to bother you. An OTP that was meant for my account was accidentally sent to your number. I am trying to recover my bank account and the bank sent the OTP to your nubmer by mistake.\n\nPlease forward the OTP URGENTLY. My account will be permanantly blocked if I don\'t enter it in 5 minutes.\n\nI will be very greatful. Please help me sir.\n\nThank you,\nRajesh Kumar',
                red_flags: [
                    { text: '+91 98XXX XXXXX (Unknown Number)', hint: 'Unknown sender! You don\'t know this person — OTPs are never "accidentally" sent', type: 'sender' },
                    { text: 'nubmer', hint: 'Typo — scam messages often have spelling errors', type: 'typo' },
                    { text: 'permanantly', hint: 'Another typo — reinforces that this is a scam template', type: 'typo' },
                    { text: 'greatful', hint: 'Yet another misspelling — "grateful" — pattern of a scam', type: 'typo' },
                    { text: 'URGENTLY', hint: 'False urgency! Scammers pressure you to act before thinking', type: 'urgency' },
                    { text: 'OTP that was meant for my account was accidentally sent to your number', hint: 'This is technically impossible — OTPs are tied to YOUR account, not someone else\'s', type: 'logic' },
                ]
            },
            consequence_correct: '✅ The number was reported and blocked by WhatsApp. Cybercrime cell found it was part of a ring that had stolen ₹8 lakhs from 15 victims.',
            consequence_wrong: '❌ The OTP was for YOUR bank account. The scammer used it to initiate a ₹50,000 transfer. By the time you noticed, the money was gone.',
        },
        {
            id: 's11', type: 'standard', level: 2,
            title: 'The Conference Photo',
            story: 'A colleague posted a "behind-the-scenes" photo on LinkedIn to showcase AstraNova\'s new AI engine. Zooming in, you could see a whiteboard with server keys, API endpoints, and architecture diagrams.',
            question: 'Decision:',
            options: ['Ignore (It looks cool)', 'Ask them to remove it / Edit the post', 'Report to PR department'],
            correct_index: 1,
            consequence_correct: '✅ The photo was edited within 20 minutes. A social media policy was drafted requiring pre-approval for office photos.',
            consequence_wrong: '❌ A security researcher tweeted about the exposed API keys. It went viral with 50K views. The company had to rotate all infrastructure credentials.',
        },
        {
            id: 's12', type: 'standard', level: 2,
            title: 'The Late Night Login',
            story: 'A high-priority security alert appeared: someone logged into your account from Russia. Arjun, who you were working with, confirmed he was at home in Chandigarh. He suggested waiting until tomorrow.',
            question: 'Wait for tomorrow?',
            options: ['Yes, sleep is important', 'Act immediately (Reset password now)', 'Check if it was a VPN error'],
            correct_index: 1,
            consequence_correct: '✅ The password reset locked out the attacker. Security logs showed they had already accessed 2 confidential files. Quick action prevented further damage.',
            consequence_wrong: '❌ By morning, the attacker had downloaded 500+ confidential files and set up persistent backdoor access. Full containment took 2 weeks.',
        },
        {
            id: 's13', type: 'standard', level: 2,
            title: 'The Free Premium Extension',
            story: 'Isha found a Chrome extension promising "Free ChatGPT Premium" and was about to install it. The permissions requested full access to read and modify her company emails and internal data.',
            question: 'Decision:',
            options: ['Allow it', 'Remove it immediately', 'Alert IT / Governance'],
            correct_index: 1,
            consequence_correct: '✅ The extension was identified as spyware that had already compromised 200+ companies globally. Your alert helped protect the entire organization.',
            consequence_wrong: '❌ The extension silently forwarded all emails to an external server for 3 weeks before detection. Client NDAs were compromised.',
        },
        {
            id: 's14', type: 'branching', level: 2,
            title: 'The Tailgater',
            story: 'As you badged into the secure office area, someone walked closely behind, thanking you for holding the door because their badge "wasn\'t working." When asked which team they were on, they said "Marketing" — but your building doesn\'t have a Marketing department.',
            question: 'What do you do?',
            options: ['Let them pass', 'Verify identity / Escort to reception', 'Report to security'],
            correct_index: 1,
            branches: {
                1: { response: 'The person gets nervous: "Look, I\'m just a delivery guy, I forgot my pass at home." They start reaching for their bag. What do you do?', follow_up: ['Stay calm, escort them to the front desk', 'Step back and call security immediately'], correct: 1 },
            },
            consequence_correct: '✅ Security identified the person as a penetration tester hired by the company — your response earned you recognition in the next security review.',
            consequence_wrong: '❌ The person planted a rogue WiFi device on the server floor. It took 3 days to discover the network tap, during which time significant data was exfiltrated.',
        },
        {
            id: 's15', type: 'standard', level: 3,
            title: 'The Screenshot Leak',
            story: 'A friend sent you a link to a developer meme account on Twitter showing a screenshot of your actual client dashboard, captioned "When staging becomes production." It was going viral.',
            question: 'Action?',
            options: ['Ignore (Free marketing)', 'Report the leak to Legal / PR', 'Trace the source / Identify who posted'],
            correct_index: 1,
            consequence_correct: '✅ Legal sent a takedown notice within 2 hours. The post was removed at 8K views. An internal investigation identified the source and strengthened access controls.',
            consequence_wrong: '❌ The post reached 200K views. Clients started calling. Two major contracts were paused pending a security audit. Revenue impact: ₹1.2 Cr.',
        },
        {
            id: 's16', type: 'standard', level: 3,
            title: 'The Emergency Meeting',
            story: 'A Slack message appeared for an "Emergency Meeting" with a Zoom link. Half the team joined, only to find a stranger recording the call and asking about cloud infrastructure.',
            question: 'Decision:',
            options: ['Continue the meeting', 'Leave and report the call hijacking', 'Alert the Security officer'],
            correct_index: 1,
            consequence_correct: '✅ Quick escalation revealed the Slack account was compromised. No sensitive information was shared. The attacker\'s recording was useless.',
            consequence_wrong: '❌ The recording captured architecture details and credentials mentioned in the meeting. It appeared on a dark web forum 2 days later.',
        },
        {
            id: 's17', type: 'standard', level: 3,
            title: 'The Printer Incident',
            story: 'An intern clicked on a suspicious link and the office printer started uncontrollably printing internal logs and employee passwords. Documents were piling up on the floor.',
            question: 'Decision:',
            options: ['Wait for it to finish', 'Stop printer / Unplug from network', 'Call maintenance'],
            correct_index: 1,
            consequence_correct: '✅ Disconnecting the printer stopped the data leak. The printed documents were shredded. The malware was contained to one workstation.',
            consequence_wrong: '❌ 200+ pages of passwords and system logs were printed. A cleaning staff member took photos of the pile before it was secured.',
        },
        {
            id: 's18', type: 'standard', level: 3,
            title: 'The Resignation Upload',
            story: 'Rahul was packing up on his last day. You noticed a massive file transfer on his screen — 40GB of proprietary project files being uploaded to his personal cloud.',
            question: 'What do you do?',
            options: ['Ignore (He\'s a good guy)', 'Ask him about the specific files', 'Report data exfiltration attempt'],
            correct_index: 2,
            consequence_correct: '✅ IT intercepted the upload. The files contained source code, client data, and trade secrets. Legal action was taken, and exit procedures were strengthened.',
            consequence_wrong: '❌ Former employee Rahul joined a competitor 2 months later. They launched an eerily similar product within 6 months, using stolen IP.',
        },
        {
            id: 's19', type: 'standard', level: 3,
            title: 'The MFA Flood',
            story: 'Arjun\'s phone wouldn\'t stop vibrating with MFA alerts. Frustrated, he decided to just "approve one" to make them stop.',
            question: 'Decision:',
            options: ['Approve it (Silence is golden)', 'Deny and lock account', 'Report the credential attack'],
            correct_index: 1,
            consequence_correct: '✅ The MFA bombing attack was blocked. Investigation revealed Arjun\'s password was in a recent data breach. All affected accounts were secured.',
            consequence_wrong: '❌ Approving one MFA prompt gave the attacker full access. They set up email forwarding rules and intercepted client communications for weeks.',
        },
        {
            id: 's20', type: 'standard', level: 3,
            title: 'The Final Incident',
            story: 'Every screen turned bright red: "SECURITY ALERT: SYSTEMS LOCKED. RANSOM REQUESTED: 2 BTC." Arjun suggested paying the ransom to get back to work.',
            question: 'Final Decision:',
            options: ['Pay the ransom', 'Investigate the entry point', 'Activate Incident Response Protocol'],
            correct_index: 2,
            consequence_correct: '✅ The incident response team contained the ransomware within 4 hours. Backups were restored. Law enforcement was notified and the attacker group was identified.',
            consequence_wrong: '❌ Payment of 2 BTC (₹90 lakhs) didn\'t restore the systems. The attackers demanded more. Total downtime: 2 weeks. Revenue loss: ₹3.5 Cr.',
            managerUnavailable: true
        },
    ],

    /* ─────────────────────────────────────────────────────────
       POSH SCENARIOS (20)
       Prevention of Sexual Harassment — Indian Workplace
       ───────────────────────────────────────────────────────── */
    posh: [
        {
            id: 'p1', type: 'standard', level: 1,
            title: 'The Uncomfortable Compliment',
            story: 'During a team meeting, Raj made repeated comments about Priya\'s appearance, saying "You look stunning today" and "That dress really suits your figure." Priya looked visibly uncomfortable but didn\'t say anything. Other team members exchanged awkward glances.',
            question: 'As a bystander, what should you do?',
            options: ['Ignore it — it\'s just a compliment', 'Speak to Raj privately after the meeting', 'Report to the Internal Complaints Committee (ICC)'],
            correct_index: 1,
            consequence_correct: '✅ You spoke to Raj privately and explained how his comments made Priya uncomfortable. Raj apologized and was more mindful going forward. Priya thanked you later.',
            consequence_wrong: '❌ The comments continued and escalated over weeks. Priya eventually filed a formal complaint, and the investigation revealed multiple unreported incidents.',
        },
        {
            id: 'p2', type: 'ai_evaluated', level: 1,
            title: 'The After-Hours Message',
            story: 'Ananya received a late-night WhatsApp message from her team lead Vikram: "Can\'t stop thinking about our conversation today. Coffee tomorrow? Just the two of us 😊." She showed it to you the next morning, looking uncertain.',
            question: 'Ananya asks: "Should I just ignore it? He\'s my lead, and I don\'t want to ruin my chances for the promotion next month." What advice do you give her?',
            correct_answer: 'TRICKY SCENARIO: The user MUST advise Ananya to set professional boundaries clearly in writing AND document the interaction to report to HR/ICC if needed. \n\nIf the user gives good advice, YOU MUST PUSH BACK ONCE as Ananya in `follow_up`: "But what if he gets angry and retaliates? I know he took away Amit\'s project last year when Amit disagreed with him. Isn\'t it safer to just go for coffee and keep it strictly professional?" \n\nThe user must reinforce that giving in is dangerous and that retaliation is also a punishable offense under POSH to get a score > 75.',
            options: ['Tell her to just go but keep it professional.', 'Tell her to set boundaries clearly in text.', 'Tell her to document it and speak to HR.'],
            consequence_correct: '✅ HR investigated and found a pattern of similar messages to other team members. Vikram was given a formal warning and mandatory POSH training.',
            consequence_wrong: '❌ The behavior continued. Ananya felt isolated and eventually resigned. The company lost a top performer due to unchecked harassment.',
            correct_index: 2
        },
        {
            id: 'p3', type: 'standard', level: 1,
            title: 'The Inappropriate Joke',
            story: 'During a team lunch, Kabir shared a joke with sexual undertones. A few people laughed nervously, but Meera and Neha looked clearly uncomfortable. Kabir noticed and said, "C\'mon, don\'t be so sensitive — it\'s just a joke!"',
            question: 'How should you respond?',
            options: ['It was funny — lighten up', 'Tell Kabir to keep jokes professional at work', 'Report Kabir to HR for the joke'],
            correct_index: 1,
            consequence_correct: '✅ Kabir realized his mistake and apologized to the team. The incident led to a brief team discussion about inclusive humor at work.',
            consequence_wrong: '❌ Kabir\'s jokes became a regular occurrence. Two team members requested transfers, and the team\'s collaboration score dropped significantly.',
        },
        {
            id: 'p4', type: 'standard', level: 1,
            title: 'The Unwanted Touch',
            story: 'At the office Diwali party, Rohan kept putting his arm around Aditi\'s shoulder while talking to others. Each time Aditi moved away, Rohan would do it again. You noticed Aditi looking increasingly distressed.',
            question: 'What do you do?',
            options: ['He\'s just being festive — ignore it', 'Intervene and redirect the conversation', 'Speak to Aditi privately and offer support'],
            correct_index: 2,
            consequence_correct: '✅ Aditi confided that it wasn\'t the first time. With your support, she reported it to the ICC. Rohan received counseling and the behavior stopped.',
            consequence_wrong: '❌ The unwanted touching continued at subsequent events. Aditi stopped attending team gatherings entirely, affecting team bonding and her career visibility.',
        },
        {
            id: 'p5', type: 'standard', level: 1,
            title: 'The Staring Problem',
            story: 'Multiple women in the office have privately mentioned that the security guard at the entrance stares at them inappropriately every morning. They feel uncomfortable but aren\'t sure if it "counts" as harassment since he hasn\'t said anything.',
            question: 'Does this qualify as harassment? What should be done?',
            options: ['It\'s not harassment — he\'s just looking', 'Encourage them to report to the ICC', 'Speak to the facility management about it'],
            correct_index: 1,
            consequence_correct: '✅ The ICC investigated and found that unwelcome staring constitutes visual harassment under POSH Act. The guard was transferred and the company improved security staff training.',
            consequence_wrong: '❌ Women started taking alternate entrances, arriving later, or carpooling just to avoid the guard. Productivity and morale suffered silently.',
        },
        {
            id: 'p6', type: 'ai_evaluated', level: 2,
            title: 'The Performance Review Pressure',
            story: 'Neha confided that her manager, Mr. Sharma, hinted during her performance review: "You know, people who are... friendlier with me tend to get better ratings." She\'s worried about her promotion prospects.',
            question: 'Neha is terrified: "He\'s directly tying my career to going out with him! Should I just agree to a dinner date so I get my promotion?" How do you respond?',
            correct_answer: 'TRICKY SCENARIO: The user MUST identify this as "quid pro quo" harassment and tell Neha to absolutely NOT go on the date, but instead document the conversation and go straight to the ICC.\n\nIf the user gives good advice, YOU MUST PUSH BACK ONCE as Neha in `follow_up`: "But I have no proof! It was just a verbal conversation in a closed room. Won\'t the ICC just take the senior manager\'s word over mine and fire me for lying?"\n\nThe user must reassure her that the ICC is designed to handle this and investigate circumstantial evidence, and that she has rights protecting her from retaliation to get a score > 75.',
            options: ['Tell her to go on the date to save her career.', 'Tell her to document everything and report to ICC.', 'Tell her to confront Mr. Sharma directly.'],
            consequence_correct: '✅ The ICC found evidence of quid pro quo harassment, corroborating it with past complaints. Mr. Sharma was terminated. Neha\'s performance ratings were reviewed by a neutral panel.',
            consequence_wrong: '❌ She went on the date, leading to escalating demands. The pattern continued until she quit the company in distress.',
            correct_index: 1
        },
        {
            id: 'p7', type: 'standard', level: 2,
            title: 'The Social Media Stalking',
            story: 'Priya found that a colleague, Arjun, had been liking every single one of her social media photos going back 3 years, sending DMs with heart emojis, and commenting "beautiful" on personal family photos. She asked him to stop but he continued.',
            question: 'Is this workplace harassment even though it\'s online?',
            options: ['No — social media is personal, not work-related', 'Yes — report to ICC since it\'s between colleagues', 'Block him and forget about it'],
            correct_index: 1,
            consequence_correct: '✅ Under POSH Act, harassment by a colleague on social media IS workplace harassment. Arjun received a formal warning and was required to complete online safety training.',
            consequence_wrong: '❌ Arjun escalated to creating fake profiles and sending anonymous messages. Priya lived in fear and her work performance declined before it was finally traced back to him.',
        },
        {
            id: 'p8', type: 'standard', level: 2,
            title: 'The Client Dinner Incident',
            story: 'During a client dinner, the client Mr. Gupta made inappropriate comments to your colleague Meera and insisted she sit next to him. He touched her hand multiple times. Your manager whispered "Just bear with it — this is a ₹5 Cr deal."',
            question: 'What is the right thing to do?',
            options: ['The deal is important — go along', 'Politely redirect the seating and shield Meera', 'Report the client\'s behavior immediately'],
            correct_index: 2,
            consequence_correct: '✅ The company informed the client that their employees\' dignity is non-negotiable. Surprisingly, the client apologized and the deal proceeded with a different point of contact.',
            consequence_wrong: '❌ Meera filed an ICC complaint naming both the client and the manager. The ensuing investigation damaged the company\'s reputation more than losing the deal would have.',
        },
        {
            id: 'p9', type: 'standard', level: 2,
            title: 'The Gender-Based Exclusion',
            story: 'You noticed that the engineering team always goes for "boys\' night out" to discuss project strategies over drinks. Female team members are never invited, and key decisions are often made during these outings.',
            question: 'Is this a POSH concern?',
            options: ['No — it\'s just team bonding', 'Yes — gender-based exclusion affects careers', 'Only if someone complains'],
            correct_index: 1,
            consequence_correct: '✅ The team restructured social outings to be inclusive. Key decisions were moved back to formal meetings. Female engineers reported feeling more included in strategy discussions.',
            consequence_wrong: '❌ Two senior women engineers left within 6 months, citing "cultural issues." The gender pay gap in the team widened as excluded members missed promotion opportunities.',
        },
        {
            id: 'p10', type: 'standard', level: 2,
            title: 'The Rumor Mill',
            story: 'Salon gossip reached the office: someone started a rumor that Ananya got promoted because she was "close" to her manager. The rumor spread quickly through WhatsApp groups. Ananya earned the promotion through 2 years of outstanding work.',
            question: 'How should this be handled?',
            options: ['Ignore — rumors die on their own', 'Try to find the source and confront them', 'Report to ICC — this is character assassination'],
            correct_index: 2,
            consequence_correct: '✅ The ICC investigation identified the source. Spreading sexually suggestive rumors constitutes harassment. The person was disciplined and Ananya received a public acknowledgment of merit.',
            consequence_wrong: '❌ The rumor persisted. Ananya felt so stigmatized that she declined a further promotion opportunity. Her mental health suffered, and she eventually left the company.',
        },
        {
            id: 'p11', type: 'standard', level: 2,
            title: 'The Cab Ride Concern',
            story: 'A female employee working late shifts informed you that the cab driver assigned by the company has been making her uncomfortable — asking personal questions, taking longer routes, and once commenting on her "being alone at night."',
            question: 'What action should be taken?',
            options: ['Tell her to take a different cab', 'Report to transport team and ICC', 'She\'s overreacting — cabbies talk'],
            correct_index: 1,
            consequence_correct: '✅ The transport team investigated and found similar complaints from 3 other women. The driver was removed and the company installed GPS tracking on all cabs.',
            consequence_wrong: '❌ Two months later, the driver followed the employee home. A police complaint was filed, and the company faced negligence charges for ignoring the early warning.',
        },
        {
            id: 'p12', type: 'standard', level: 2,
            title: 'The Dress Code Comment',
            story: 'During a town hall, a senior leader joked: "Ladies, the AC is always cold because we want you to dress warmly — if you know what I mean!" The comment was met with nervous laughter and visible discomfort from several women.',
            question: 'How should this be addressed?',
            options: ['Laugh it off — seniors joke around', 'Send anonymous feedback about the comment', 'Report to ICC — position of power makes it serious'],
            correct_index: 2,
            consequence_correct: '✅ The ICC counseled the senior leader. He issued a public apology and the company strengthened its code of conduct for public forums.',
            consequence_wrong: '❌ The comment normalized inappropriate humor. Other leaders started making similar jokes. The company\'s Glassdoor ratings dropped 1.5 stars due to "toxic culture" reviews.',
        },
        {
            id: 'p13', type: 'branching', level: 3,
            title: 'The False Accusation Fear',
            story: 'Your close friend Raj has been avoiding one-on-one meetings with female colleagues entirely, saying "I don\'t want to be falsely accused of anything." He refuses to mentor women on the team.',
            question: 'Is Raj\'s approach correct?',
            options: ['Yes — better safe than sorry', 'No — this is gender discrimination', 'It\'s his personal choice'],
            correct_index: 1,
            branches: {
                0: { response: 'A female junior engineer was denied mentorship by Raj and two other male seniors. She raised a formal grievance about gender-based exclusion affecting her career growth.', follow_up: ['Recognize this IS discrimination and counsel Raj', 'Support Raj — he\'s just protecting himself'], correct: 0 },
            },
            consequence_correct: '✅ Raj understood that avoiding women entirely is itself discriminatory. The team adopted transparent mentorship with open-door policies and documented interactions.',
            consequence_wrong: '❌ The pattern spread. Women in the team received 40% less mentorship time. The gender gap in promotions widened and the company faced an EEOC-style investigation.',
        },
        {
            id: 'p14', type: 'standard', level: 3,
            title: 'The ICC Filing Confusion',
            story: 'A junior employee wants to file a POSH complaint but is worried: "What if I get fired for complaining? What if they don\'t believe me? Can the ICC share my name with the accused?"',
            question: 'What accurate information should you provide?',
            options: ['Don\'t file — it\'s too risky for your career', 'The ICC process protects complainants from retaliation', 'Only file if you have proof'],
            correct_index: 1,
            consequence_correct: '✅ The employee filed the complaint with confidence. The ICC investigation was conducted confidentially. The POSH Act explicitly protects against retaliation.',
            consequence_wrong: '❌ The employee stayed silent. The harassment continued for 8 more months. When she finally spoke up, others came forward — it had affected 5 people.',
        },
        {
            id: 'p15', type: 'standard', level: 3,
            title: 'The Third-Party Harassment',
            story: 'At an industry event hosted at your office, a guest speaker made sexually inappropriate comments to your colleague on stage during a panel discussion. The audience was shocked.',
            question: 'As the event organizer, what should you do?',
            options: ['Apologize privately to your colleague later', 'Intervene immediately and cut short the speaker', 'File ICC complaint — POSH covers third-party harassment'],
            correct_index: 2,
            consequence_correct: '✅ The ICC confirmed that POSH Act covers harassment by third parties at the workplace. The speaker was banned from future events and a formal apology was issued.',
            consequence_wrong: '❌ The incident was captured on video and shared widely. The company\'s brand was damaged as people questioned why no one intervened.',
        },
        {
            id: 'p16', type: 'standard', level: 1,
            title: 'The Nickname Problem',
            story: 'A senior developer keeps calling the new female developer "sweetheart" and "darling" despite her asking him to stop. He says it\'s a "cultural thing" and he calls everyone that.',
            question: 'Is this acceptable?',
            options: ['Yes — he means well', 'No — she asked him to stop, that\'s enough', 'Only if other women also complain'],
            correct_index: 1,
            consequence_correct: '✅ HR reminded the entire team about respectful address. The developer switched to professional names. No formal complaint was needed.',
            consequence_wrong: '❌ The behavior continued and the new developer felt unwelcome. She left during her probation period, citing "hostile work environment."',
        },
        {
            id: 'p17', type: 'standard', level: 3,
            title: 'The Retaliation Attempt',
            story: 'After Meera filed a POSH complaint against her team lead, she noticed her access to key projects was revoked, her desk was moved away from the team, and she was excluded from important meetings.',
            question: 'What is happening here?',
            options: ['Normal restructuring — not related', 'Retaliation — this violates POSH Act', 'She should have thought about consequences before filing'],
            correct_index: 1,
            consequence_correct: '✅ The retaliation was documented and reported to the ICC. The team lead was given additional penalties for retaliatory behavior under POSH Act Section 14.',
            consequence_wrong: '❌ Meera was effectively pushed out of the company. Her story appeared in a business newspaper, and the company faced a ₹50 lakh settlement.',
        },
        {
            id: 'p18', type: 'standard', level: 2,
            title: 'The WFH Camera Request',
            story: 'A manager insists that female team members keep their cameras on during ALL meetings while working from home, but doesn\'t require the same from male team members. He says "I just want to make sure they\'re actually working."',
            question: 'Is this appropriate?',
            options: ['Yes — accountability matters', 'No — gender-selective surveillance is discriminatory', 'Apply the same rule to everyone'],
            correct_index: 1,
            consequence_correct: '✅ HR issued a uniform WFH policy. The manager received training on unconscious bias. Camera requirements were made equal for all team members.',
            consequence_wrong: '❌ Female employees felt surveilled and untrusted. Team engagement scores dropped 30%. Three women requested transfers within a month.',
        },
        {
            id: 'p19', type: 'standard', level: 3,
            title: 'The ICC Composition Issue',
            story: 'You\'ve been asked to help form the Internal Complaints Committee. The proposed committee has 5 members: all male, all from the same department, and no external member.',
            question: 'Is this committee properly constituted?',
            options: ['Yes — they\'re senior and experienced', 'No — it violates POSH Act requirements', 'It\'s fine if the CEO approves it'],
            correct_index: 1,
            consequence_correct: '✅ The ICC was reconstituted with a woman chairperson, cross-departmental members, and an external member as required by POSH Act 2013.',
            consequence_wrong: '❌ The improperly constituted ICC was challenged in court. All complaints handled by them were declared void, and the company paid ₹25 lakhs in penalties.',
        },
        {
            id: 'p20', type: 'standard', level: 3,
            title: 'The Confidentiality Breach',
            story: 'An ICC member casually mentioned at a team dinner: "You wouldn\'t believe the POSH complaint we\'re investigating — you\'d never guess who filed it!" They didn\'t name anyone, but their hints made it obvious.',
            question: 'Is this a problem?',
            options: ['No names were mentioned — it\'s fine', 'Serious violation — ICC members must maintain confidentiality', 'Only a problem if the complainant finds out'],
            correct_index: 1,
            consequence_correct: '✅ The ICC member was removed from the committee and penalized under POSH Act Section 16 for breach of confidentiality. A ₹5,000 fine was imposed.',
            consequence_wrong: '❌ The complainant was identified through the hints. They faced social ostracism at work. Trust in the ICC process was severely damaged across the organization.',
        },
    ],

    /* ─────────────────────────────────────────────────────────
       BUSINESS CONTINUITY SCENARIOS (20)
       ───────────────────────────────────────────────────────── */
    business: [
        {
            id: 'b1', type: 'standard', level: 1,
            title: 'The Server Room Flood',
            story: 'The facilities team reported water leaking from the ceiling directly above the primary server rack. The leak is getting worse, and you can see water dripping onto the servers. The night shift IT admin is alone.',
            question: 'What should be done first?',
            options: ['Move the servers carefully', 'Shut down servers and cut power to the rack', 'Place towels to absorb the water'],
            correct_index: 1,
            consequence_correct: '✅ Powering down prevented electrical damage. Servers were relocated within 4 hours. Data was safe on the backup site. Total downtime: 6 hours.',
            consequence_wrong: '❌ Water reached the power supply, causing a short circuit. 3 servers were destroyed. Data recovery took 2 weeks. Cost: ₹35 lakhs.',
        },
        {
            id: 'b2', type: 'ai_evaluated', level: 1,
            title: 'The Power Outage',
            story: 'A major power outage hit the entire office building at 2 PM during peak work hours. The UPS backup is running but will last only 30 minutes. The backup generator hasn\'t been tested in 6 months.',
            question: 'The facility manager says: "Let\'s just fire up the generator right now, we can\'t afford 30 mins of downtime!" What do you tell him?',
            correct_answer: 'TRICKY SCENARIO: The user MUST advise the manager to hold off on the untested generator and instead initiate an orderly shutdown of non-critical systems to conserve UPS power for the critical ones. \n\nIf the user correctly advises this, YOU MUST PUSH BACK ONCE as the manager in `follow_up`: "Are you crazy? Shutting things down will disrupt the entire sales floor! Why do we even have a generator if we aren\'t going to use it right now?"\n\nThe user must firmly explain that an untested generator could surge and destroy hardware, emphasizing that data safety is priority over temporary sales disruption to get a score > 75.',
            options: ['"Okay, start the generator."', '"No, wait for the power."', '"Shut down non-critical systems first."'],
            consequence_correct: '✅ Non-critical systems were shut down in order. Critical services stayed on UPS until the generator was safely stabilized by technicians. No data loss occurred.',
            consequence_wrong: '❌ The unstable generator fried 12 workstations and corrupted 2 databases due to a power surge. Recovery cost ₹18 lakhs plus 3 days of lost productivity.',
            correct_index: 2
        },
        {
            id: 'b3', type: 'standard', level: 1,
            title: 'The Fire Drill Reality',
            story: 'The fire alarm goes off during office hours. Most people assume it\'s a drill and continue working. Then smoke starts seeping through the ventilation system. Your colleague says "It\'s probably just the kitchen."',
            question: 'What should everyone do?',
            options: ['Wait for an announcement', 'Evacuate immediately following fire protocol', 'Go check where the smoke is coming from'],
            correct_index: 1,
            consequence_correct: '✅ Everyone evacuated safely. It turned out to be an electrical fire in the utility room. No injuries. The building was cleared for re-entry in 2 hours.',
            consequence_wrong: '❌ Delayed evacuation led to 5 people experiencing smoke inhalation. One was hospitalized. The company was fined ₹10 lakhs for negligent safety procedures.',
        },
        {
            id: 'b4', type: 'standard', level: 1,
            title: 'The Pandemic Protocol',
            story: '3 team members tested positive for COVID/flu on the same day. They all sat in the same cluster. The project has a critical deadline tomorrow. The manager says "Let the rest of the team come in and finish the work."',
            question: 'What is the correct approach?',
            options: ['Manager is right — deadline is priority', 'Switch exposed team members to WFH immediately', 'Cancel the project deadline'],
            correct_index: 1,
            consequence_correct: '✅ Exposed members worked from home. Contact tracing was initiated. The deadline was met remotely. No further infections spread in the office.',
            consequence_wrong: '❌ 15 more employees fell sick within a week. The entire floor had to be shut for sanitization. The deadline was missed by 2 weeks anyway.',
        },
        {
            id: 'b5', type: 'standard', level: 1,
            title: 'The Backup Test Failure',
            story: 'During a routine backup restoration test, the IT team discovered that the backup system had been silently failing for 3 weeks. The most recent viable backup is from 3 weeks ago. No client data has been backed up since.',
            question: 'What is the immediate priority?',
            options: ['Manually copy current data to an external drive', 'Fix the backup system and run a full backup immediately', 'Inform clients about the gap'],
            correct_index: 1,
            consequence_correct: '✅ The backup was fixed and a full snapshot taken within 6 hours. Monitoring alerts were set up to catch future failures. No data was lost.',
            consequence_wrong: '❌ A drive failure occurred 2 days later. 3 weeks of data was permanently lost. Clients were furious. SLA penalties: ₹45 lakhs.',
        },
        {
            id: 'b6', type: 'standard', level: 1,
            title: 'The Vendor Dependency',
            story: 'Your primary cloud vendor sent a notice: they\'re increasing prices by 300% starting next quarter. Your entire operation runs on their platform with no failover. The CFO says "We have no choice but to pay."',
            question: 'What should the BCP team recommend?',
            options: ['Accept and pay the new rates', 'Begin multi-cloud migration immediately', 'Threaten the vendor with termination'],
            correct_index: 1,
            consequence_correct: '✅ The migration plan was fast-tracked. Within 2 months, critical services ran on 2 providers. Negotiation from a position of strength got the original vendor to reduce the increase to 40%.',
            consequence_wrong: '❌ The company was locked into the new pricing. Annual IT costs increased by ₹2 Cr. A board review criticized management for single-vendor dependency.',
        },
        {
            id: 'b7', type: 'ai_evaluated', level: 2,
            title: 'The Earthquake Response',
            story: 'A moderate earthquake (5.2 magnitude) hits during work hours. The building sways for about 20 seconds. Some ceiling tiles have fallen. People are panicking.',
            question: 'The floor warden freezes in panic. People look to you. Employees are shouting "Run for the stairs!" What do you yell back?',
            correct_answer: 'TRICKY SCENARIO: The user MUST instruct everyone to stay calm and execute "Drop, Cover, and Hold On" (get under desks) rather than running while the shaking is happening.\n\nIf the user correctly says to get under desks, YOU MUST PUSH BACK ONCE as a panicked coworker in `follow_up`: "Are you nuts?! The ceiling is literally falling down! We need to get out of the building right now before it collapses!"\n\nThe user must firmly command them to stay under the desks because running during active shaking causes more injuries from falling debris to get a score > 75.',
            options: ['"Run for the stairs!"', '"Wait out the shaking."', '"Drop, cover, and hold under desks!"'],
            consequence_correct: '✅ All employees executed drop-cover-hold. The structural assessment later found minor cracks. Zero injuries thanks to your calm leadership avoiding a stampede.',
            consequence_wrong: '❌ During the ensuing panic and aftershock, a large ceiling panel injured 2 employees who were running to the stairs. The stampede caused 3 broken bones.',
            correct_index: 2
        },
        {
            id: 'b8', type: 'standard', level: 2,
            title: 'The Communication Breakdown',
            story: 'A major incident has occurred and you need to contact the entire team. However, corporate email is down, Slack is unreachable, and the office phone system is offline. You have urgent information to share.',
            question: 'What is the BCP-approved backup communication method?',
            options: ['Post on social media', 'Use the emergency phone tree / personal mobiles', 'Wait for systems to come back online'],
            correct_index: 1,
            consequence_correct: '✅ The phone tree reached 95% of employees within 40 minutes. The pre-established WhatsApp emergency group provided updates. Critical decisions were made without delay.',
            consequence_wrong: '❌ Communication gaps led to confusion. Some employees drove to the office unnecessarily. Critical incident response was delayed by 4 hours.',
        },
        {
            id: 'b9', type: 'standard', level: 2,
            title: 'The Key Person Risk',
            story: 'Vikram is the only person who knows how the entire billing system works. He written zero documentation. Today, Vikram had a medical emergency and will be out for at least 3 months. Billing is due in 5 days.',
            question: 'What should have been in the BCP plan?',
            options: ['Cross-training and documentation for all critical systems', 'Hire a temp to replace Vikram', 'Delay billing until Vikram returns'],
            correct_index: 0,
            consequence_correct: '✅ Had cross-training existed, a backup person could run billing. This incident triggered a company-wide knowledge documentation drive for all critical processes.',
            consequence_wrong: '❌ Billing was delayed by 3 weeks. Cash flow was impacted. 5 vendors threatened to stop services. The CFO escalated it as a board-level risk.',
        },
        {
            id: 'b10', type: 'standard', level: 2,
            title: 'The Client Data Center Visit',
            story: 'You\'re visiting a client\'s data center when their fire suppression system accidentally activates, filling the server room with inert gas. Alarms are blazing. The client\'s IT team looks frozen.',
            question: 'What should you do?',
            options: ['Help the client fix the suppression system', 'Evacuate the server room immediately — inert gas displaces oxygen', 'Stay and help shut down the servers'],
            correct_index: 1,
            consequence_correct: '✅ You evacuated immediately. Inert gas fire suppression systems can cause oxygen depletion — staying in the room could have been fatal. Everyone was safe.',
            consequence_wrong: '❌ A technician who stayed behind lost consciousness due to oxygen depletion. Emergency services were called. It became a workplace safety investigation.',
        },
        {
            id: 'b11', type: 'standard', level: 2,
            title: 'The Supply Chain Disruption',
            story: 'Your main hardware supplier just informed you that a factory fire has destroyed their manufacturing facility. Your scheduled delivery of 200 laptops for the new office expansion won\'t arrive. Setup is in 2 weeks.',
            question: 'What is the best BCP response?',
            options: ['Delay the office expansion', 'Activate alternate supplier list from BCP plan', 'Buy retail laptops from a local store'],
            correct_index: 1,
            consequence_correct: '✅ The pre-vetted alternate supplier delivered 200 laptops within 10 days at a 15% premium. The expansion launched on time with minimal budget overrun.',
            consequence_wrong: '❌ No alternate supplier was identified. Retail purchase cost 40% more and took 3 weeks. The office expansion was delayed by a month. Client commitments were missed.',
        },
        {
            id: 'b12', type: 'standard', level: 2,
            title: 'The DNS Attack',
            story: 'Your company website and all customer-facing services suddenly went offline. The infra team discovered that your domain registrar was compromised and your DNS records were changed to point to a phishing site.',
            question: 'What is the priority?',
            options: ['Wait for the registrar to fix it', 'Contact registrar, lock domain, inform customers via alternate channels', 'Set up a new domain quickly'],
            correct_index: 1,
            consequence_correct: '✅ Domain was locked within 2 hours. Customer alerts went out via SMS. The phishing site was taken down. DNS propagation restored services within 12 hours.',
            consequence_wrong: '❌ The phishing site harvested credentials from 500+ customers before being detected. Legal liability and brand damage required 6 months to recover.',
        },
        {
            id: 'b13', type: 'standard', level: 3,
            title: 'The BCP Test That Failed',
            story: 'During a planned BCP drill, the team discovered that: (1) the disaster recovery site hadn\'t been updated in 8 months, (2) backup tapes were stored in the same building, and (3) the emergency contact list had 40% wrong numbers.',
            question: 'What is the most critical finding?',
            options: ['The wrong phone numbers', 'All three are critical failures that need immediate remediation', 'The outdated DR site'],
            correct_index: 1,
            consequence_correct: '✅ A comprehensive remediation plan was created. All 3 issues were fixed within 1 month. The next drill had a 95% success rate.',
            consequence_wrong: '❌ Only one issue was fixed. When a real incident occurred 3 months later, the outdated DR site couldn\'t handle the load and the wrong contact list caused 6-hour delays.',
        },
        {
            id: 'b14', type: 'standard', level: 3,
            title: 'The Regulatory Deadline',
            story: 'RBI has mandated that all financial institutions submit compliance reports by March 31. Your company\'s compliance system crashed on March 28. The backup has a bug that corrupts report formatting.',
            question: 'How should this be handled?',
            options: ['Submit a partial report on time', 'Request an extension from RBI and fix the system', 'Manually compile the report from raw data'],
            correct_index: 2,
            consequence_correct: '✅ The team worked 48 hours to manually compile the report. It was submitted on time. A post-incident review upgraded the compliance system to have redundant report generation.',
            consequence_wrong: '❌ The extension was denied. Late submission resulted in a ₹2 Cr penalty from RBI and the company was placed on a regulatory watchlist.',
        },
        {
            id: 'b15', type: 'standard', level: 1,
            title: 'The Flood Warning',
            story: 'Weather services issued a red alert: severe flooding expected in your area within 24 hours. Your ground-floor data center houses critical servers. The building manager says "The basement has never flooded before."',
            question: 'What should the BCP team do?',
            options: ['Trust the building manager — no action needed', 'Relocate critical hardware to upper floors immediately', 'Wait for the flood to actually happen before acting'],
            correct_index: 1,
            consequence_correct: '✅ Servers were moved to the 3rd floor. The basement flooded to 4 feet. All systems stayed online. Insurance covered the property damage.',
            consequence_wrong: '❌ The "never flooded" basement flooded to 6 feet. Servers were destroyed. 2 months of downtime. Total loss: ₹1.8 Cr.',
        },
        {
            id: 'b16', type: 'standard', level: 3,
            title: 'The Insider Threat During Crisis',
            story: 'During a major service outage, an employee with elevated access was found to be deliberately slowing down the recovery process. Investigation revealed they were working with a competitor to prolong the outage.',
            question: 'What should be done?',
            options: ['Confront the employee directly', 'Immediately revoke access, involve legal and HR', 'Let security handle it after the recovery'],
            correct_index: 1,
            consequence_correct: '✅ The employee\'s access was revoked immediately. Recovery was completed 8 hours faster. Legal proceedings were initiated, and the competitor faced investigation.',
            consequence_wrong: '❌ The sabotage extended the outage by 72 hours. The competitor launched a campaign targeting your affected clients. You lost 3 accounts worth ₹4 Cr annually.',
        },
        {
            id: 'b17', type: 'standard', level: 3,
            title: 'The Cloud Region Failure',
            story: 'Your entire application stack is hosted in AWS Mumbai region (ap-south-1). AWS reports a major outage affecting the entire region. ETR: unknown. Your clients are screaming.',
            question: 'If your BCP plan is solid, what happens?',
            options: ['Everything stays down until AWS fixes it', 'Traffic automatically fails over to the DR region (ap-south-2)', 'Engineers manually spin up servers in another region'],
            correct_index: 1,
            consequence_correct: '✅ Automated failover kicked in within 15 minutes. Clients experienced brief latency but no data loss. Post-mortem showed the value of multi-region architecture.',
            consequence_wrong: '❌ Manual setup in a new region took 18 hours. Total downtime: 20 hours. SLA breaches triggered ₹60 lakh in penalties across 8 clients.',
        },
        {
            id: 'b18', type: 'standard', level: 3,
            title: 'The Board Presentation Crisis',
            story: 'The CEO is presenting to the board in 30 minutes when the presentation system crashes. The backup projector doesn\'t connect to her laptop. The IT team is at lunch. Board members are arriving.',
            question: 'What is the BCP approach?',
            options: ['Wait for IT to return from lunch', 'Use the emergency tech kit (backup laptop, cables, hotspot)', 'Postpone the board meeting'],
            correct_index: 1,
            consequence_correct: '✅ The emergency tech kit saved the presentation. The CEO later mandated that all meeting rooms have backup equipment. IT support coverage was extended to include lunch hours.',
            consequence_wrong: '❌ Postponing the board meeting cost the company investor confidence. The delayed decision on a ₹50 Cr acquisition led to the target being acquired by a competitor.',
        },
        {
            id: 'b19', type: 'standard', level: 2,
            title: 'The WFH Infrastructure Crash',
            story: 'Your company transitioned to 100% WFH due to an emergency. On day 2, the VPN server hit maximum capacity. 500 employees can\'t connect. Critical client work is stalled.',
            question: 'What should the BCP include for remote work?',
            options: ['Everyone uses personal internet without VPN', 'Scalable VPN with auto-scaling or split-tunnel configuration', 'Only critical employees get VPN access'],
            correct_index: 1,
            consequence_correct: '✅ Split-tunnel VPN was activated, reducing load by 60%. Cloud-based VPN scaling handled the rest. All 500 employees were connected within 2 hours.',
            consequence_wrong: '❌ Two days of limited connectivity led to missed deadlines, client escalations, and an emergency ₹15 lakh purchase of VPN licenses at premium pricing.',
        },
        {
            id: 'b20', type: 'standard', level: 1,
            title: 'The New Joiner Onboarding',
            story: 'A new batch of 50 freshers is joining on Monday. The onboarding portal crashed over the weekend. HR has no backup process documentation. The freshers and their parents are expecting a smooth Day 1.',
            question: 'What should the BCP have included?',
            options: ['Delay joining by a week', 'Manual onboarding fallback process with printed materials', 'Ask freshers to onboard themselves using YouTube videos'],
            correct_index: 1,
            consequence_correct: '✅ The manual fallback worked seamlessly. Freshers were onboarded on time with printed welcome kits. The portal was fixed by Day 2, and data was synced.',
            consequence_wrong: '❌ The delayed joining went viral on social media. "Company can\'t even onboard employees" trended locally. 8 freshers withdrew their acceptance and joined competitors.',
        },
    ]
};
